artifact_location: /Users/josealberto/Documents/GitHub/Mlops-platzi/tracking/experiments_ml/398101700129282801
creation_time: 1780000671884
experiment_id: '398101700129282801'
last_update_time: 1780000671884
lifecycle_stage: active
name: iris_experiment_ml_local
